### ISSUE TITLE
Initial filter ranges

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-frontend#11]
Currently the filter initial state is hardcoded.

The filter should be automatically initialised according to the maximum ranges in the Jobdatabase. This requires a API to aquire min max values for all filter values.

**Comment by moebiusband73** [comment]
The filter ranges should update according to the Cluster that is selected.

**Comment by iamlouk** [comment]
I got confused trying to amend to a previous commit, this issue was worked on in 094f9a7d75312996f04cdf7f4ddea8af71bc60ec (I originally wanted that to be two separate commits, sorry).

Leaving this issue open to quickly discuss something related: When the user selects a cluster, for now, the filters are changed to represent the full range of values for that cluster. This means prev. changes to settings like duration are thrown away. Would it maybe be better to clamp the values? Or leave them as they are even if they lie outside the range of values for that newly selected cluster?

**Comment by moebiusband73** [comment]
Thats a good point. I would suggest to not throw the current settings away but only reset them if they are outside of the new cluster ranges and clamp them if this is the case.

**Comment by iamlouk** [comment]
Closed in 6345aaf9910779c25875f4787a5359474712b958.
